name: Merge Dev to Master

on:
 push:
  branches:
   - dev

permissions:
 contents: write

jobs:
 merge-to-main:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
   uses: actions/checkout@v4
   with:
    fetch-depth: 0

  - name: Fetch All Branches
   run: git fetch --all

  - name: Ensure Main Branch Exists
   run: |
    git fetch origin master || echo "Branch main does not exist yet"

  - name: Switch to Main Branch
   run: |
    git checkout master || git checkout -b master origin/master
    git pull origin master --rebase

  - name: Update Dev Branch
   run: git pull origin dev --rebase

  - name: Debug Git Status
   run: git status

  - name: Merge Dev into Main
   run: |
    git merge dev --no-ff -m "Merge dev into main"
    git push origin master