name: Merge Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write  # Memberikan izin untuk menulis ke repo

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch All Branches
      run: git fetch --all

    - name: Merge Dev into Main
      run: |
        git checkout main
        git merge dev
        git push origin main