name: Merge Dev to Master

on:
 push:
  branches:
   - dev

permissions:
 contents: write

jobs:
 merge-to-master:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
   uses: actions/checkout@v4
   with:
    fetch-depth: 0

  - name: Fetch All Branches
   run: git fetch --all

  - name: Configure Git User
   run: |
    git config --global user.name "dimasrn"
    git config --global user.email "dimas.bhp10037@gmail.com"

  - name: Merge Dev into Master
   run: |
    git checkout master
    git merge dev --no-ff -m "Merge dev into master"
    git push origin master